- Agilex_Cobot_Magic
- Agilex_Split_Aloha
- Airbot_MMK2
- Galaxea_R1_Lite
- Realman_RMC-AIDA-L
- Robotera_Q5
- Unitree_G1edu-u3
- Galbot_G1
- Leju_Kuavo_4_LB
- Leju_Kuavo_4_Pro
- Tianqing_A2
- Tianqing_A2D
- AI2_Alphabot_1s
- AI2_Alphabot_2
- Realman_Rs-01
- Realman_Rs-02
- AgiBot-g1
- G1edu-u3
- RMC-AIDA-L
- Rs-02
- Rs-01
