realman_rmc_aidal: 
- version: default_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.realman_rmc_aidal_processor
  post_processor_class: RealmanRmcAidalProcessor

- version: mcap_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.realman_rmc_aidal_processor
  post_processor_class: RealmanRmcAidalMcapProcessor

# - version: mcap_simple_version
#   post_processor_module: robocoin_dataset.state_action_data_post_process.processors.realman_rmc_aidal_processor
#   post_processor_class: RealmanRmcAidalProcessor

galaxea_r1_lite:
- version: default_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.galaxea_r1_lite_processor
  post_processor_class: GalaxeaR1LiteProcessor

- version: h5_mp4_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.galaxea_r1_lite_processor
  post_processor_class: GalaxeaR1LiteH5Mp4Processor

agilex_cobot_decoupled_magic:
- version: default_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.agilex_cobot_decoupled_magic_processor
  post_processor_class: AgilexCobotDecoupledMagicProcessor

- version: realsense_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.agilex_cobot_decoupled_magic_processor
  post_processor_class: AgilexCobotDecoupledRealsenseMagicProcessor

- version: headdown_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.agilex_cobot_decoupled_magic_processor
  post_processor_class: AgilexCobotDecoupledMagicProcessor

- version: mult_sensor
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.agilex_cobot_decoupled_magic_processor
  post_processor_class: AgilexCobotDecoupledMagicMultSensorProcessor

- version: h5_mp4
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.agilex_cobot_decoupled_magic_processor
  post_processor_class: AgilexCobotDecoupledMagicH5Mp4Processor

- version: h5_mp4_new
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.agilex_cobot_decoupled_magic_processor
  post_processor_class: AgilexCobotDecoupledMagicH5Mp4Processor
  
unitree_g1:
- version: default_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.unitree_g1_processor
  post_processor_class: UnitreeG1FiveFingerHandProcessor

- version: threecam_dex3v1_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.unitree_g1_processor
  post_processor_class: UnitreeG1Processor

- version: twocam_hand_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.unitree_g1_processor
  post_processor_class: UnitreeG1ThreeFingerOutProcessor

- version: dex3v1_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.unitree_g1_processor
  post_processor_class: UnitreeG1Processor

discover_robotics_aitbot_mmk2:
- version: third_view
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.discover_robotics_aitbot_mmk2_processor
  post_processor_class: ThirdViewProcessor

- version: third_view
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.discover_robotics_aitbot_mmk2_processor
  post_processor_class: ThirdViewProcessor

- version: third_view_lite
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.discover_robotics_aitbot_mmk2_processor
  post_processor_class: FivedArmsProcessor

ruantong_a2d:
- version: default_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.ruantong_a2d_processor
  post_processor_class: RuantongA2dProcessor

- version: gt01_no_depth
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.ruantong_a2d_processor
  post_processor_class: RuantongA2dProcessor

- version: gt02_new_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.ruantong_a2d_processor
  post_processor_class: RuantongA2dGt02Processor

leju_robot:
- version: waibu_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.leju_robot_processor
  post_processor_class: LejuRobotProcessor

- version: waibu_lite
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.leju_robot_processor
  post_processor_class: LejuRobotProcessor

yinhe:
- version: default_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.yinhe_processor
  post_processor_class: YinheProcessor

- version: lite_version
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.yinhe_processor
  post_processor_class: YinheProcessor

alpha_bot_2:
- version: dual_arm_with_pose
  post_processor_module: robocoin_dataset.state_action_data_post_process.processors.alpha_bot_2_processor
  post_processor_class: AlphaBot2Processor
