dataset_data_checkers:
  - name: "few_episode_frames"
    params:
      threshold: 150
    should_check: True  

  - name: "too_few_episodes"
    params:
      threshold: 30
    should_check: True  

  - name: "abnormal_episode_length"
    params:
      threshold: 4.0
    should_check: True  

episode_data_checkers:
  - name: "static_frame_rate"
    params:
      window_size: 5
      threshold: 0.01
    should_check: True  
    score_weight: 1.0   

  - name: "static_joint"
    params:
      static_joints_percent: 0.4
      epsilon: 0.001
    should_check: True  
    score_weight: 1.0   
