### fps by manual
fps: 30
features:
  observation:
    images:
      # Leju robot cameras
      - cam_name: cam_high_rgb
        args:
          image_key: head_cam_h
      - cam_name: cam_right_wrist_rgb
        args:
          image_key: wrist_cam_r
      - cam_name: cam_left_wrist_rgb
        args:
          image_key: wrist_cam_l

    state:
      ### values by function
      # lerobot_feature: observation.state : by _gen_lerobot_features()
      # dtype: float32 
      # shape: [26]  

      ## sub_states should be concatenated together here : by _gen_state_names()
      
      ### values by manual
      sub_state:

      - names: 
      - l_leg_roll
      - l_leg_yaw
      - l_leg_pitch
      - l_knee
      - l_foot_pitch
      - l_foot_roll
      - r_leg_roll
      - r_leg_yaw
      - r_leg_pitch
      - r_knee
      - r_foot_pitch
      - r_foot_roll
      - l_arm_pitch
      - l_arm_roll
      - l_arm_yaw
      - l_forearm_pitch
      - l_hand_yaw
      - l_hand_pitch
      - l_hand_roll
      - r_arm_pitch
      - r_arm_roll
      - r_arm_yaw
      - r_forearm_pitch
      - r_hand_yaw
      - r_hand_pitch
      - r_hand_roll

      args:
          ### keys and values by manual
          json_path: observation.state
          range_from: 0
          range_to: 26

  action:
    ### values by function
    # lerobot_feature: action : by _gen_lerobot_features()
    # dtype: float32
    # shape: [26]  
    ## sub_actions should be concatenated together here : by _gen_action_names()

    ### values by manual
    sub_action:
    - names: 
      - l_leg_roll
      - l_leg_yaw
      - l_leg_pitch
      - l_knee
      - l_foot_pitch
      - l_foot_roll
      - r_leg_roll
      - r_leg_yaw
      - r_leg_pitch
      - r_knee
      - r_foot_pitch
      - r_foot_roll
      - l_arm_pitch
      - l_arm_roll
      - l_arm_yaw
      - l_forearm_pitch
      - l_hand_yaw
      - l_hand_pitch
      - l_hand_roll
      - r_arm_pitch
      - r_arm_roll
      - r_arm_yaw
      - r_forearm_pitch
      - r_hand_yaw
      - r_hand_pitch
      - r_hand_roll

      args:
        ### keys and values by manual
        json_path: action
        range_from: 0
        range_to: 26
