### fps by manual
fps: 30
features:
  observation:
    images:

    ### values by manual
    - cam_name: head_color
      args:
      args:
        ### key and values by manual
        h5_path: camera/{frame_idx}/head_color.jpg
        file_type: jpg


      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.head_color : by _gen_lerobot_features()
        

    # ### values by manual
    # - cam_name: head_depth  # LeRobot不支持depth，已注释
    #   args:
    #     ### keys and values by manual
    #     h5_path: camera/{frame_idx}/head_depth.png
    #     file_type: png
    #   ### values by function
    #   # dtype: video
    #   # shape: [480, 640, 3]
    #   # names: [height, width, channels]
    #   # lerobot_feature: observations.images.head_depth : by _gen_lerobot_features()

    ### values by manual
    - cam_name: hand_left_color
      args:
      args:
        h5_path: camera/{frame_idx}/hand_left_color.jpg
        file_type: jpg

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.hand_left_color : by _gen_lerobot_features()

    ### values by manual
    - cam_name: hand_right_color
      args:
      args:
        h5_path: camera/{frame_idx}/hand_right_color.jpg
        file_type: jpg

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.hand_right_color : by _gen_lerobot_features()

    ### values by manual
    - cam_name: back_left_fisheye_color
      args:
      args:
        h5_path: camera/{frame_idx}/back_left_fisheye_color.jpg
        file_type: jpg

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.back_left_fisheye_color : by _gen_lerobot_features()

    ### values by manual
    - cam_name: back_right_fisheye_color
      args:
      args:
        h5_path: camera/{frame_idx}/back_right_fisheye_color.jpg
        file_type: jpg

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.back_right_fisheye_color : by _gen_lerobot_features()

    ### values by manual
    - cam_name: head_center_fisheye_color
      args:
      args:
        h5_path: camera/{frame_idx}/head_center_fisheye_color.jpg
        file_type: jpg

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.head_center_fisheye_color : by _gen_lerobot_features()

    ### values by manual
    - cam_name: head_left_fisheye_color
      args:
      args:
        h5_path: camera/{frame_idx}/head_left_fisheye_color.jpg
        file_type: jpg

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.head_left_fisheye_color : by _gen_lerobot_features()

    ### values by manual
    - cam_name: head_right_fisheye_color
      args:
      args:
        h5_path: camera/{frame_idx}/head_right_fisheye_color.jpg
        file_type: jpg

      ### values by function
      # dtype: video
      # shape: [480, 640, 3]
      # names: [height, width, channels]
      # lerobot_feature: observations.images.head_right_fisheye_color : by _gen_lerobot_features()


    state:
      ### values by function
      # lerobot_feature: observation.state : by _gen_lerobot_features()
      # dtype: float32 
      # shape: [41]

      ## sub_states should be concatenated together here : by _gen_state_names(), such as:
      # names: 
      # - joint_pos_0
      # - ...
      # - joint_pos_13
      # - ...
      sub_state:
      - names: 
        - left_arm_joint_1_rad
        - left_arm_joint_2_rad
        - left_arm_joint_3_rad
        - left_arm_joint_4_rad
        - left_arm_joint_5_rad
        - left_arm_joint_6_rad
        - left_arm_joint_7_rad

        args:
        args:
          h5_path: /state/joint/position
          range_from: 0
          range_to: 7
        
        ### values by manual
        convert_func: to_float32
      
      - names: 
        - right_arm_joint_1_rad
        - right_arm_joint_2_rad
        - right_arm_joint_3_rad
        - right_arm_joint_4_rad
        - right_arm_joint_5_rad
        - right_arm_joint_6_rad
        - right_arm_joint_7_rad

        args:
        args:
          h5_path: /state/joint/position
          range_from: 7
          range_to: 14

        ### values by manual
        convert_func: to_float32

      ### values by manual
      - names: 
        - left_end_pos_x_m
        - left_end_pos_y_m
        - left_end_pos_z_m
        args:
        args:
          h5_path: /state/end/position
          range_from: 0
          range_to: 3
          array_index: 0

        ### values by manual
        convert_func: to_float32

      - names: 
        - left_end_quat_x
        - left_end_quat_y
        - left_end_quat_z
        - left_end_quat_w

        args:
          ### keys and values by manual
          h5_path: /state/end/orientation
          range_from: 0
          range_to: 4
          array_index: 0
        
        convert_func: quat_xyzw_2_euler_xyz
        ### values by manual
        convert_func: to_float32


      ### values by manual
      - names: 
        - right_end_pos_x_m
        - right_end_pos_y_m
        - right_end_pos_z_m

        args:
        args:
          h5_path: /state/end/position
          range_from: 0
          range_to: 3
          array_index: 1

        ### values by manual
        convert_func: to_float32

      ### values by manual
      - names: 
        - right_end_quat_x
        - right_end_quat_y
        - right_end_quat_z
        - right_end_quat_w
        args:
          ### keys and values by manual
          h5_path: /state/end/orientation
          range_from: 0
          range_to: 4
          array_index: 1

        convert_func: quat_xyzw_2_euler_xyz
        ### values by manual
        convert_func: to_float32

      - names: 
        - waist_yaw_rad
        - waist_pitch_rad

        args:
        args:
          h5_path: /state/waist/position
          range_from: 0
          range_to: 2
        
        ### values by manual
        convert_func: to_float32

      - names: 
        - head_yaw_rad
        - head_pitch_rad

        args:
        args:
          h5_path: /state/head/position
          range_from: 0
          range_to: 2
        
        ### values by manual
        convert_func: to_float32

      - names: 
        - left_effector_open_deg
        - right_effector_open_deg

        args:
          ### keys and values by manual
          h5_path: /state/effector/position
          range_from: 0
          range_to: 2
        
        convert_func: degree2rad
        ### values by manual
        convert_func: to_float32

      - names: 
        - robot_pos_x_m
        - robot_pos_y_m
        - robot_pos_z_m

        args:
        args:
          h5_path: /state/robot/position
          range_from: 0
          range_to: 3
        
        ### values by manual
        convert_func: to_float32

      - names: 
        - robot_quat_x
        - robot_quat_y
        - robot_quat_z
        - robot_quat_w

        args:
          ### keys and values by manual
          h5_path: /state/robot/orientation
          range_from: 0
          range_to: 4
        
        convert_func: quat_xyzw_2_euler_xyz
        ### values by manual
        convert_func: to_float32


  action:
    ### values by function
    # lerobot_feature: observation.action: by _gen_lerobot_features()
    # dtype: float32 
    # shape: [34]

    ## sub_actions should be concatenated together here, : by _gen_acton_names(), such as:
    # names:
    # - joint_pos_0
    # - ...
    # - joint_pos_13
    # - ...

    ### values by manual
    timeline_offset: 1
    sub_action:

      - names: 
        - left_arm_joint_1_rad
        - left_arm_joint_2_rad
        - left_arm_joint_3_rad
        - left_arm_joint_4_rad
        - left_arm_joint_5_rad
        - left_arm_joint_6_rad
        - left_arm_joint_7_rad

        args:
        args:
          h5_path: /action/joint/position
          range_from: 0
          range_to: 7
        
        ### values by manual
        convert_func: to_float32
      
      - names: 
        - right_arm_joint_1_rad
        - right_arm_joint_2_rad
        - right_arm_joint_3_rad
        - right_arm_joint_4_rad
        - right_arm_joint_5_rad
        - right_arm_joint_6_rad
        - right_arm_joint_7_rad

        args:
        args:
          h5_path: /action/joint/position
          range_from: 7
          range_to: 14

        ### values by manual
        convert_func: to_float32

      ### values by manual
      - names: 
        - left_end_pos_x_m
        - left_end_pos_y_m
        - left_end_pos_z_m
        args:
        args:
          h5_path: /action/end/position
          range_from: 0
          range_to: 3
          array_index: 0

        ### values by manual
        convert_func: to_float32

      - names: 
        - left_end_quat_x
        - left_end_quat_y
        - left_end_quat_z
        - left_end_quat_w

        args:
          ### keys and values by manual
          h5_path: /action/end/orientation
          range_from: 0
          range_to: 4
          array_index: 0
        
        convert_func: quat_xyzw_2_euler_xyz
        ### values by manual
        convert_func: to_float32


      ### values by manual
      - names: 
        - right_end_pos_x_m
        - right_end_pos_y_m
        - right_end_pos_z_m

        args:
        args:
          h5_path: /action/end/position
          range_from: 0
          range_to: 3
          array_index: 1

        ### values by manual
        convert_func: to_float32

      ### values by manual
      - names: 
        - right_end_quat_x
        - right_end_quat_y
        - right_end_quat_z
        - right_end_quat_w
        args:
          ### keys and values by manual
          h5_path: /action/end/orientation
          range_from: 0
          range_to: 4
          array_index: 1

        convert_func: quat_xyzw_2_euler_xyz
        ### values by manual
        convert_func: to_float32

      - names: 
        - waist_yaw_rad
        - waist_pitch_rad

        args:
        args:
          h5_path: /action/waist/position
          range_from: 0
          range_to: 2
        
        ### values by manual
        convert_func: to_float32

      - names: 
        - head_yaw_rad
        - head_pitch_rad

        args:
        args:
          h5_path: /action/head/position
          range_from: 0
          range_to: 2
        
        ### values by manual
        convert_func: to_float32

      - names: 
        - left_effector_open_deg
        - right_effector_open_deg

        args:
          ### keys and values by manual
          h5_path: /action/effector/position
          range_from: 0
          range_to: 2
        
        convert_func: degree2rad
        ### values by manual
        convert_func: to_float32